### ISSUE TITLE
Historikk for svar og kommentarer

### ISSUE THREAD

**Issue by perzonas** [kartverket/regelrett#148]
Vi vil vise historikken og koblingen mellom svar og kommentarer for hvert spørsmål til brukeren

```[tasklist]
### Tasks
- [ ] #147 
- [ ] #144 
- [ ] https://github.com/kartverket/regelrett/issues/151
- [ ] https://github.com/kartverket/regelrett/issues/150
- [ ] https://github.com/kartverket/regelrett/issues/149
```
