### ISSUE TITLE
Ny redigeringsside for kontrollere

### ISSUE THREAD

**Issue by malinnsnieske** [kartverket/regelrett#259]
Man skal kunne trykke på ID'en til en spesifikk kontroller og da gå inn på en ny side. Der skal det være mulig å redigere samt se historikken.
```[tasklist]
### Tasks
- [ ] https://github.com/kartverket/regelrett/issues/262
- [ ] https://github.com/kartverket/regelrett/issues/263
- [ ] https://github.com/kartverket/regelrett/issues/264
- [ ] https://github.com/kartverket/regelrett/issues/265
- [ ] https://github.com/kartverket/regelrett/issues/266
- [ ] https://github.com/kartverket/regelrett/issues/267
- [ ] https://github.com/kartverket/regelrett/issues/166
- [ ] https://github.com/kartverket/regelrett/issues/309
- [ ] https://github.com/kartverket/regelrett/issues/326
- [ ] https://github.com/kartverket/regelrett/issues/334
- [ ] https://github.com/kartverket/regelrett/issues/340
```
