### ISSUE TITLE
Forskjellige svartyper til spørsmål

### ISSUE THREAD

**Issue by starheim98** [kartverket/regelrett#278]
Finnes kun dropdown (single select) svartype for øyeblikket. Må endre AirTable til å inkludere svartype og eventuelle svaralternativer for hvert spørmål.

Endringen av AirTable vil medføre at database, backend og frontend må oppdateres til å håndtere forskjellige svartyper
```[tasklist]
### Tasks
- [ ] https://github.com/kartverket/regelrett/issues/279
- [ ] https://github.com/kartverket/regelrett/issues/282
- [ ] https://github.com/kartverket/regelrett/issues/283
- [ ] https://github.com/kartverket/regelrett/issues/292
- [ ] https://github.com/kartverket/regelrett/issues/293
```
